# Site settings
name: VizLab
description: ""
intro: What's down there
baseurl: "/blog" 
url: "http://akadealloc.github.io" 


# Build settings
markdown: kramdown
highlighter: pygments
permalink:    pretty

# Owner/author information
owner:
  name:           Jayson
  avatar:         ""
  email:          Jayson.xu@foxmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:		ecs_tee
  github:		akadealloc

