# Site settings
baseurl: /blog 
url: http://akadealloc.github.io
title: What's Down There?
#url: 127.0.0.1
#baseurl:

# Build settings
#markdown: redcarpet
markdown: kramdown
highlighter: pygments
redcarpet:
  extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]


#user info:
twitter_username: ecs_tee
github_username:  akadealloc
email: jayson.xu@foxmail.com

