# Site settings
name: VizLab
email: Jayson.xu@foxmail.com
description: ""
intro: What's down there
url: "http://akadealloc.github.io"
baseurl: "/blog"
twitter_username: ecs_tee
github_username:  akadealloc
logo:             logo.png


css:
  css_dir: /css/
sass:
  sass_dir: /css/
  style: :compressed

# Build settings
paginate: 8
markdown: redcarpet
permalink:    pretty
