# Site settings
baseurl: /blog 
url: http://akadealloc.github.io

#url: 127.0.0.1
#baseurl:

# Build settings
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]


# Owner/author information
owner:
  name:           Jayson
  avatar:         ""
  email:          Jayson.xu@foxmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:		ecs_tee
  github:		akadealloc

